version: "3.9"
services:

  node:
    build:
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    env_file:
      - .env
    volumes:
      - ./data:/var/data
    depends_on:
      - db
    command: /var/app/node_modules/.bin/ts-node /var/app/src/app.ts

  db:
    restart: always
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_TEST_DATABASE=${DATABASE_TEST_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE

volumes:
  db-data:
    name: ${DB_VOLUME_NAME}
