#!/bin/bash

echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};" | mysql -u root -p"${MYSQL_ROOT_PASSWORD}"
echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_TEST_DATABASE};" | mysql -u root -p"${MYSQL_ROOT_PASSWORD}"

echo "GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION" | mysql -u root -p"${MYSQL_ROOT_PASSWORD}"
